PORTFOLIO_ROOT_DIR: "{{ lookup('env','PORTFOLIO_ROOT_DIR') }}"
AWS_ACCESS_KEY_ID: !vault |
                    $ANSIBLE_VAULT;1.2;AES256;user
                    30636330353937373466313931316664356235323061393531353564303535346366343162646635
                    3038336463663531663335376635303336343262666339340a613233643934663164366337613666
                    39333839323430336532316138393437356239356465316565326232666633626465383864366337
                    3532326531303630630a626563613433373138363337353166303666663165626535663639373334
                    39313431633663323338626436336261323439303461616239323465336134363734

AWS_SECRET_ACCESS_KEY: !vault |
                    $ANSIBLE_VAULT;1.2;AES256;user
                    32666230656161336235346563343432303935363639343266306163333763663439313163383665
                    3837306438373231663936653236633430343138646435310a306536363035353134393865313931
                    31336332383830393137383466656333383535323935613561393239393431616339366637643230
                    3333653930636537620a633838383034396139323262613233623733323463343338356535303164
                    34373834393766616630306133643637653531616338346438346137393134616130626361343031
                    3766636663643661393138313961326463316639366434316535