- name: Send Slack notification
  slack:
    token: '{{ SLACK_TOKEN }}'
    msg: 'ðŸš€ðŸ’« App is up for {{ QA_INSTANCE_TIME_MINUTES }}mn! (http://{{ ANSIBLE_DEV_HOSTNAME }}:{{ ANSIBLE_APP_PORT }}) ðŸ’«ðŸš€'
  delegate_to: localhost