ANSIBLE_USER: ec2-user
DOCKER_GROUP: docker
DOCKER_COMPOSE_VERSION: "1.25.0"
DOCKER_USER: "{{ lookup('env','DOCKER_USER') }}"
DOCKER_PASSWORD: !vault |
            $ANSIBLE_VAULT;1.2;AES256;user
            33393434353132616431386365613834336139306164353763653666656638386261663037356434
            6531643566643134303665306534393133303439636337640a646366336131306531396132626232
            33313433313939626231646365343037363933666133363264363634393935653134306565623862
            6361356333333664660a643833393332616661353534333162626662373231666139316238346536
            6437